# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5

development:
  <<: *default
  database: decks_dev
  username: luca.mattiazzi

production:
  <<: *default
  host: ec2-54-228-246-206.eu-west-1.compute.amazonaws.com
  database: hoplite-database
  username: nfincxmbghonhj
  password: 12rf9DnDQtmIuxirM4BZWuSUx
